"""The `_tracker.md` format — parsed one way, rendered the other.

Both directions live here on purpose: it is a single file format, and a reader kept
apart from its writer is a format that drifts. Pure functions — no DB, no filesystem —
which is what makes onboarding's import path cheap to test.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Literal, TypedDict

TODO = "todo"
DONE = "done"

_HEADING = re.compile(r"^\s{0,3}#{2,3}\s+(.*?)\s*$")
_CHECKBOX = re.compile(r"^\s*[-*]\s*\[([ xX])\]\s+(.*?)\s*$")
# hand-written headings trail pointers/markers: "Phase 4 — Core data model ← THE STORE ✅"
_HEADING_NOISE = re.compile(r"\s*(←.*|✅|🔴|⚠️)\s*$")


class TrackerItem(TypedDict):
    """The plain-dict shape exchanged at the repository/tracker_md boundary.

    `repository.import_items`, `repository.items_with_folders`, and
    `render_tracker_md` all agree on this shape — it is the untyped seam between
    them, so one definition here keeps a faithful-looking test fake from drifting
    from production. `status` stays `str` (not the stricter `Literal` used by
    `ParsedItem`) because this boundary must still accept whatever a caller hands
    it — `import_items` coerces anything but todo/done to todo, it doesn't reject it.
    """

    title: str
    status: str
    folder: str | None


@dataclass
class ParsedItem:
    """One work item recovered from a markdown checklist."""

    title: str
    status: Literal["todo", "done"]
    folder: str | None = None


@dataclass
class ParsedTracker:
    items: list[ParsedItem] = field(default_factory=list)

    @property
    def folders(self) -> list[str]:
        """Folder names in first-seen order, de-duplicated."""
        seen: dict[str, None] = {}
        for item in self.items:
            if item.folder:
                seen.setdefault(item.folder, None)
        return list(seen)


def _clean_heading(text: str) -> str:
    previous = None
    while previous != text:
        previous = text
        text = _HEADING_NOISE.sub("", text)
    return text.strip()


def parse_tracker_md(text: str) -> ParsedTracker:
    """Recover items from a hand-written checklist/guidance markdown file.

    `##`/`###` headings become folder names; `- [ ]` / `- [x]` lines become items.
    Blockquotes are skipped so a file's own "Rules: `[x]` done" preamble is not
    imported as work. Only `todo`/`done` are inferred — richer statuses are the
    user's to set, never guessed.
    """
    parsed = ParsedTracker()
    folder: str | None = None
    for line in text.splitlines():
        if line.lstrip().startswith(">"):
            continue
        heading = _HEADING.match(line)
        if heading:
            folder = _clean_heading(heading.group(1)) or None
            continue
        box = _CHECKBOX.match(line)
        if box:
            status = DONE if box.group(1).lower() == "x" else TODO
            parsed.items.append(ParsedItem(title=box.group(2), status=status, folder=folder))
    return parsed


UNFILED = "Items"

_GENERATED_BANNER = (
    "<!-- Generated by `trackden` from the database. Do not edit by hand:\n"
    "     your edits will be overwritten. Change state via the CLI or the MCP tools. -->"
)


def is_generated(text: str) -> bool:
    """Is this text a trackden-generated `_tracker.md` mirror, not human-authored?

    The generated file always carries this fixed banner. Anything containing it is
    derived output — a mirror of the DB, never a source of truth — and callers that
    scan a repo for importable checklists must skip it rather than re-import it.
    """
    return _GENERATED_BANNER in text


def render_tracker_md(project_name: str, items: list[TrackerItem]) -> str:
    """Render the DB's items as the generated `_tracker.md` mirror.

    Derived output, never a source of truth — the banner says so to whoever opens it.
    Items are grouped under their folder name; unfiled items go under `UNFILED`.
    """
    groups: dict[str, list[dict]] = {}
    for item in items:
        groups.setdefault(item.get("folder") or UNFILED, []).append(item)

    done = sum(1 for item in items if item.get("status") == DONE)
    lines = [
        f"# {project_name} — tracker (GENERATED)",
        "",
        _GENERATED_BANNER,
        "",
        f"**Progress:** {done} / {len(items)} done.",
        "",
    ]
    for folder, group in groups.items():
        lines.append(f"## {folder}")
        for item in group:
            box = "x" if item.get("status") == DONE else " "
            lines.append(f"- [{box}] {item['title']}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"
